=== cristoferarmando/XMLCHRISTOPHER/public/data/museo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="listapinturas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pinturas" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="artista">
                                <xs:complexType>
                                    <xs:attribute name="nombre" use="required" />
                                    <xs:attribute name="apellido" use="required" />
                                    <xs:attribute name="nacionalidad" use="required" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="release" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== cristoferarmando/XMLCHRISTOPHER/public/data/museo.xml
<?xml version="1.0" encoding="UTF-8"?>

<listapinturas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="museo.xsd">
    <pinturas>
        <nombre>la noche estrellada</nombre>
        <artista nombre="Vincent" apellido="Van Gogh" nacionalidad="Netherlands" />        
        <release>1889</release>       
    </pinturas>
        
    <pinturas>
        <nombre>autorretrato</nombre>
        <artista nombre="Vincent" apellido="Van Gogh" nacionalidad="Netherlands" />        
        <release>1889</release>
    </pinturas>

    <pinturas>
        <nombre> Los girasoles </nombre>
        <artista nombre="Vincent" apellido="Van Gogh" nacionalidad="Netherlands" />        
        <release> - </release>
    </pinturas>

</listapinturas>
